[build]
builder = "dockerfile"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
RAILWAY_STARTUP_TIMEOUT = "300"